Djtube/Djtube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('', include('users.urls'), name='users'),
    path('', include('social.apps.django_app.urls'), name='social'),
    path('posts/', include('posts.urls'), name='posts'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

Djtube/posts/urls.py
from django.urls import path

from posts.views import *


app_name = 'posts'
urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('new/', PostCreateView.as_view(), name='create'),
    path('confirm/', PostCreateConfirmView.as_view(), name='confirm'),
    path('<slug:slug>/', PostDetailView.as_view(), name='detail')
]

Djtube/users/urls.py
from django.urls import path

from users.views import *


app_name = 'users'
urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

Djtube/posts/models/post.py
from django.db import models
from django.urls import reverse
from users.models import User


class Post(models.Model):

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    hash_id = models.CharField(
        max_length=8,
        blank=True,
        null=True
    )
    video_id = models.CharField(
        max_length=16,
    )
    video_original_title = models.CharField(
        max_length=256,
        blank=True,
        null=True,
    )

    title = models.CharField(
        max_length=256,
    )
    content = models.TextField()

    thumbnail_image = models.ImageField(
        blank=True,
        null=True
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_thumbnail_image_url(self):
        if self.thumbnail_image:
            return self.thumbnail_image.url
        return self.youtube_thumbnail_image_url
    thumbnail_image_url = property(get_thumbnail_image_url)

    def get_youtube_thumbnail_image_url(self):
        from posts.utils.youtube import get_youtube_thumbnail_image_url
        return get_youtube_thumbnail_image_url(self.video_id)
    youtube_thumbnail_image_url = property(get_youtube_thumbnail_image_url)

    def get_youtube_original_url(self):
        from posts.utils.youtube import get_youtube_original_url as get_youtube_original_url_from_video_id
        return get_youtube_original_url_from_video_id(self.video_id)
    youtube_original_url = property(get_youtube_original_url)

    def get_youtube_embed_url(self):
        from posts.utils.youtube import get_youtube_embed_url as get_youtube_embed_url_from_video_id
        return get_youtube_embed_url_from_video_id(self.video_id)
    youtube_embed_url = property(get_youtube_embed_url)

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={
            "slug": self.hash_id,
        })

Djtube/users/models/user.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    phonenumber = models.CharField(
        max_length=16,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.phonenumber

Djtube/Djtube/views.py
from django.shortcuts import render
from django.views import View


class Home(View):
    def get(self, request):
        return render(self.request, 'home.html')

Djtube/posts/views/base.py
from django.views.generic import View

from posts.models import Post


class PostBaseView(View):
    model = Post

Djtube/posts/views/create.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View

from posts.models import Post
from posts.utils import youtube


class PostCreateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(
            request,
            'posts/new.html',
            context={},
        )

    def post(self, request, *args, **kwargs):
        video_id = request.POST.get('video_id')
        title = request.POST.get('title')
        content = request.POST.get('content')

        thumbnail_image = request.FILES.get("thumbnail_image")

        post = request.user.post_set.create(
            video_id=video_id,
            title=title,
            content=content,
            thumbnail_image=thumbnail_image,
        )

        return redirect(post)


class PostCreateConfirmView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return redirect(reverse('posts:create'))

    def post(self, request, *args, **kwargs):
        video_id = request.POST.get('video_id')
        title = request.POST.get('title')
        content = request.POST.get('content')

        return render(
            request,
            'posts/confirm.html',
            context={
                'video_id': video_id,
                'title': title,
                'content': content,

                "youtube_original_url": youtube.get_youtube_original_url(video_id),
                "youtube_embed_url": youtube.get_youtube_embed_url(video_id),
                "youtube_thumbnail_image_url": youtube.get_youtube_thumbnail_image_url(video_id),
            },
        )

Djtube/posts/views/detail.py
from django.views.generic.detail import DetailView
from .base import PostBaseView


class PostDetailView(PostBaseView, DetailView):
    template_name = "posts/detail.html"
    slug_field = "hash_id"

Djtube/posts/views/list.py
from django.views.generic.list import ListView
from .base import PostBaseView


class PostListView(PostBaseView, ListView):
    template_name = "posts/list.html"
    context_object_name = "posts"

Djtube/users/views/login.py
from django.contrib import messages
from django.urls import reverse
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.conf import settings


class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(
            request,
            'users/login.html',
            context={},
        )

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')

        next_url = request.POST.get('next_url') or reverse('users:login')  # FIXME: redirect to home

        user = authenticate(
            username=username,
            password=password,
        )

        if user:
            login(request, user)
            messages.add_message(
                request,
                messages.SUCCESS,
                settings.LOGIN_SUCCESS_MESSAGE
            )
            return redirect(reverse('users:login'))

        return redirect(next_url)

Djtube/users/views/logout.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import View
from django.contrib.auth import logout


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(
            request,
            messages.SUCCESS,
            settings.LOGOUT_SUCCESS_MESSAGE
        )
        return redirect(reverse('users:login'))

Djtube/users/views/signup.py
from django.conf import settings
from django.contrib import messages
from django.urls import reverse
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model


class SignupView(View):
    def get(self, request, *args, **kwargs):
        return render(
            request,
            'users/signup.html',
            context={},
        )

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        phonenumber = request.POST.get('phonenumber')

        # TODO - validations ( username )

        user = get_user_model().objects.create_user(
            username=username,
            password=password,
            phonenumber=phonenumber,
        )

        messages.add_message(
            request,
            messages.SUCCESS,
            settings.SIGNUP_SUCCESS_MESSAGE
        )

        return redirect(reverse('users:login'))

Djtube/Djtube/templates/base.html
{% load pipeline %}<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% stylesheet 'djtube' %}
    <title>{% block title %}{% endblock %}</title>
    <!--    bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
</head>
<body>
{% include "partials/navbar.html" %}
{% include "partials/messages.html" %}

<section id="content">
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</section>
{% include "partials/footer.html" %}
</body>
</html>

Djtube/Djtube/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Home</h1>
{% endblock %}

Djtube/Djtube/templates/partials/footer.html
<footer>
    <h2>Youtube Storage</h2>
    <p>유튜브 저장소</p>
</footer>

Djtube/Djtube/templates/partials/header.html
<header>
    <h1>유튜브 저장소</h1>
</header>

Djtube/Djtube/templates/partials/messages.html
{% if messages %}
<section id="messages">
    <ul>
        {% for message in messages %}
        <li class="{{ message.tags }}">
            <p>{{ message }}</p>
        </li>
        {% endfor %}
    </ul>
</section>
{% endif %}

Djtube/Djtube/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"><b>유튜브 저장소</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <b>Posts</b>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'posts:create' %}">Create</a>
                    <a class="dropdown-item" href="{% url 'posts:list' %}">List</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'users:logout' %}" tabindex="-1" aria-disabled="true">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'users:signup' %}" tabindex="-1" aria-disabled="true">Signup</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'users:login' %}" tabindex="-1" aria-disabled="true">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

Djtube/posts/templates/posts/confirm.html
{% extends 'base.html' %}

{% block content %}
{% block title %}Post - Confirm{% endblock %}
<h1>Confirm</h1>

<section>
    <h3>{{ title }}</h3>
    <p>{{ content }}</p>

    <img src="{{ youtube_thumbnail_image_url }}" alt="{{ title }}"  target="_blank">

    <a href="{{ youtube_original_url }}" target="_blank">유튜브 링크 바로가기</a>
    <br>
    <iframe
        width="500"
        height="315"
        src="{{ youtube_embed_url }}"
        frameborder="0"
        allowfullscreen></iframe>

    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>위의 정보로 포스트로 생성하시겠습니까?</p>
        <input type="hidden" name="video_id" value="{{ video_id }}">
        <input type="hidden" name="title" value="{{ title }}">
        <input type="hidden" name="content" value="{{ content }}">

        <p>현재의 썸네일 이미지가 마음에 안들면 새로운 이미지로 변경할 수 있습니다. </p>
        <input type="file" name="thumbnail_image">

        <input type="submit">
    </form>
</section>
{% endblock %}

Djtube/posts/templates/posts/detail.html
{% extends "base.html" %}

{% block content %}
<h1>Posts Detail</h1>

<section>
    <iframe
        width="500"
        height="315"
        src="{{ post.youtube_embed_url }}"
        frameborder="0"
        allowfullscreen></iframe>

    <h3>{{ post.title }}</h3>
    <h4>{{ post.video_original_title}}</h4>
    <p>{{ post.content }}</p>

    <a href="{{ youtube_original_url }}" target="_blank">유튜브 링크 바로가기</a>
</section>
{% endblock %}

Djtube/posts/templates/posts/list.html
{% extends "base.html" %}


{% block content %}
<h1>Post List</h1>
<div class="row">
    {% for post in posts %}
    <div class="card" style="width: 18rem;">
        <img src="{{ post.thumbnail_image_url }}" class="card-img-top" alt="{{ post.title }}">
        <div class="card-body">
            <h5 class="card-title"><b>{{ post.title }}</b></h5>
            <p class="card-text">{{ post.content }}</p>
            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">상세페이지 바로가기</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

Djtube/posts/templates/posts/new.html
{% extends 'base.html' %}
{% block title %}Post - Create{% endblock %}
{% block content %}

<h1>Create</h1>

<section>
    <form action="{% url 'posts:confirm' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="video_id" placeholder="Youtube video_id" required><br>
        <input type="text" name="title" placeholder="Title" required><br>
        <textarea name="content" id="" cols="30" rows="10" placeholder="Content"></textarea>
        <input type="submit" value="confirm">
    </form>
</section>
{% endblock %}

Djtube/users/templates/users/login.html
{% extends "base.html" %}

{% block title %}Account - Login{% endblock %}

{% block content %}
    <h1>Login</h1>

<section>
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="useranem" required>
        <input type="password" name="password" placeholder="password" required>
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <input type="submit" value="login">
    </form>
</section>

<section>
    <ul>
        <li><a href="{% url 'social:begin' backend='facebook' %}">Facebook Login</a></li>
        <li><a href="{% url 'social:begin' backend='facebook' %}">Kakao Login</a></li>
    </ul>
</section>
{% endblock %}

Djtube/users/templates/users/signup.html
{% extends "base.html" %}

{% block title %}Account - Signup{% endblock %}
{% block content %}
<h1>Signup</h1>


<section>
    <form action="{% url 'users:signup' %} " method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="useranem" required>
        <input type="password" name="password" placeholder="password" required>
        <input type="text" name="phonenumber" placeholder="phonenumber" required>
        <input type="submit" value="signup">
    </form>
</section>

<section>
    <ul>
        <li><a href="{% url 'social:begin' backend='facebook' %}">Facebook Signup</a></li>
        <li><a href="{% url 'social:begin' backend='facebook' %}">Kakao Signup</a></li>
    </ul>
</section>
{% endblock %}